name: Clippy

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/clippy.yml"
      - "operator/**"
      - "proxy/**"
      - "instance/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/clippy.yml"
      - "operator/**"
      - "proxy/**"
      - "instance/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./operator
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clippy check lints
        run: cargo clippy -- -D warnings
